export const complement = [
  {
    answer1: "$n(x')=n(y')=n(U)$",
    answer2: "$n(x')+n(y) = n(U)$",
    answer3: "$n(x+y) = n(U)$",
    answer4: "$n(x')+n(x)=n(U)$",
    correct_answer: 4,
    explaination:
      "$n(x')$ can be expressed as $n(y)$, the summation of them is equal to $n(U)$.",
    image: null,
    source: "dol",
    question:
      "The set of students who enrolled in mathematics class is $U$, $x$ of which is male and $y$ are female. If $x$ and $y$ are sets, What is the correct explaination using set complement$?$.",
    skillLevel: 1,
    tags: ["sets", "complement"],
  },
  {
    answer1: "$\\varnothing \\in P(A)$",
    answer2: "$\\{A\\} \\in P(A)$",
    answer3: "$\\{1,2\\} \\in P(A)$",
    answer4: "$A \\in P(A)$",
    correct_answer: 2,
    explaination:
      "$\\{A\\} \\in P(A) $can be expressed as $\\{A\\} \\subset A$, $\\{A\\}$ is not in the set of $A$",
    image: null,
    source: "dol",
    question:
      "Let $A = \\{\\varnothing, 1, 2, 3, \\{1, 2\\}\\}$ which of the following is false.",
    skillLevel: 1,
    tags: ["sets", "power set"],
  },
  {
    answer1: "$\\varnothing \\in P(A)$ but $0 \\notin P(A)$",
    answer2: "$\\varnothing \\subset P(A)$ but $1 \\not\\subset P(A)$",
    answer3: "$\\{\\varnothing} \\in P(A)$ and $\\{1\\} \\in P(A)$",
    answer4: "$\\{\\varnothing} \\subset P(A)$ and $\\{0\\} \\subset P(A)$",
    correct_answer: 4,
    explaination:
      "$\\varnothing} \\subset P(A)$ is correct but $\\{0\\} \\subset P(A) $is incorrect.",
    image: null,
    source: "dol",
    question:
      "Let $A = \\{\\varnothing, 0,1\\} $which of the following is false.",
    skillLevel: 1,
    tags: ["sets", "power set"],
  },
  {
    answer1: "e \\in P(A)",
    answer2: "{{b}} \\subset P(A)",
    answer3: "{c,d} \\subset P(A)",
    answer4: "{c} \\subset A",
    correct_answer: 2,
    explaination:
      "{{b}} \\subset P(A) can be expressed as {b} \\subset A which is true",
    image: null,
    source: "dol",
    question: "Let A = {a,b,{c,d},e,f} which of the following is true.",
    skillLevel: 1,
    tags: ["sets", "power set", "subset"],
  },
  {
    answer1: "\\varnothing \\subset A",
    answer2: "\\varnothing \\not\\subset A",
    answer3: "{1,{1}} \\subset A",
    answer4: "{{1},{1,{1}}} \\not\\subset A",
    correct_answer: 2,
    explaination:
      "\\varnothing is the subset of everyset. Therefore, {{1},{1,{1}}} \\not\\subset A is false.",
    image: null,
    source: "dol",
    question: "Let A = {\\varnothing,1,{1}} Which of these choices are false",
    skillLevel: 1,
    tags: ["sets", "subset"],
  },
  {
    answer1: "{1,6,7,8}",
    answer2: "{1,5,6,8}",
    answer3: "{1,5,6,7}",
    answer4: "{1,6,8}",
    correct_answer: 1,
    explaination: "",
    explainationImage:
      "https://cdn.discordapp.com/attachments/593800041941172235/936192100800794664/A_1.png",
    image: null,
    source: "dol",
    question:
      "A \\cup B = {1,2,3,4,5,7}, A \\cup C = {1,2,3,5,6,7,8}, A \\cup B = {1,2,3}, (A \\cap C)-B = \\varnothing and 4 \\notin A Find set C",
    skillLevel: 1,
    tags: ["sets", "subset"],
  },
  {
    answer1: "(A \\cup B) \\cap C'",
    answer2: "B \\cap (C-A)'",
    answer3: "B \\cap (A-C)",
    answer4: "A - (B \\cap C)",
    correct_answer: 2,
    explaination:
      "Analize (C-A)' then examine the overlapping areas between it and B. ",
    image:
      "https://discord.com/channels/@me/593800041941172235/936190051145101312",
    source: "dol",
    question: "What expression explains the colored part of the set",
    skillLevel: 1,
    tags: ["sets", "subset"],
  },
  {
    answer1: "2",
    answer2: "8",
    answer3: "16",
    answer4: "24",
    correct_answer: 1,
    explaination:
      "From P(A \\cap B) we can find n(A \\cap B) and from P(A \\cup B) = 64 we can find n(A \\cup B) = 6 We also know that the number of elements of P(A) is equal to P(B). Let x be the elements of A and B. We will get the equation x+2+x=6 then x = 2",
    image: null,
    source: "dol",
    question:
      "let the number of elements of P(A \\cap B) = 4 and P(A \\cup B) If the number of elements of P(A) is equal to P(B), what is the number of element of A-B",
    skillLevel: 1,
    tags: ["sets", "set compleiment"],
  },
  {
    answer1: "20",
    answer2: "28",
    answer3: "29",
    answer4: "21",
    correct_answer: 3,
    explaination:
      "We need to find what overlaps; P(A) \\cap A which is {\\varnothing,{0},{0,1}} ",
    image: null,
    source: "dol",
    question:
      "Let A = {\\varnothing,0,1,{0},{0,1}} Find the number of elements of P(A) - A",
    skillLevel: 1,
    tags: ["sets", "powerset"],
  },
  {
    answer1: "20",
    answer2: "28",
    answer3: "29",
    answer4: "21",
    correct_answer: 3,
    explaination:
      "We need to find what overlaps; P(A) \\cap A which is {\\varnothing,{0},{0,1}} ",
    image: null,
    source: "dol",
    question:
      "Let A = {\\varnothing,0,1,{0},{0,1}} Find the number of elements of P(A) - A",
    skillLevel: 1,
    tags: ["sets", "powerset"],
  },
  {
    answer1: "2",
    answer2: "3",
    answer3: "4",
    answer4: "6",
    correct_answer: 1,
    explaination:
      "Find the powerset of A then intersect it with A; P(A) \\cap A = {{a},{a,b}} n(P(A) \\cap A) = 2 ",
    image: null,
    source: "dol",
    question:
      "Let A = {a,b,{c},{a},{a,b},{b,c}} find the number of elements of P(A) \\cap A",
    skillLevel: 1,
    tags: ["sets", "powerset"],
  },
];

export const Type = [
  {
    answer1: "$\\varnothing$",
    answer2: "{{}}",
    answer3: "{{1}}",
    answer4: "{1}",
    correct_answer: 1,
    explaination:
      "Singleton set has only 1 member, but $\\varnothing$ has nothing inside of it( $\\{\\}$ )",
    hint: "Count each member of the sets",
    image: null,
    source: "Perth",
    question: "Which one is not a singleton set",
    skillLevel: 1,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "{1,2,3,…,99,100}",
    answer2: "{1,2,3,4,5}",
    answer3: "{a,b,c}",
    answer4: "{1,2,3,…}",
    correct_answer: 4,
    explaination: "Infinite set has unlimited members",
    hint: "Infinite set has more members than finite set",
    image: null,
    source: "Perth",
    question: "Which one is infinite set",
    skillLevel: 1,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "9",
    answer2: "89",
    answer3: "90",
    answer4: "82",
    correct_answer: 3,
    explaination: "Equal sets are sets that contain all same members",
    hint: "Equal sets property",
    image: null,
    source: "Perth",
    question: "If $\\A=\\{1,9,b\\} ,B=\\{1,a,81\\}$ and $A=B$ then $a+b=?$ ",
    skillLevel: 1,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "{1,{2,3,4}}",
    answer2: "{1,2,{3,{4}}}",
    answer3: "{{1,2},{3,{4,}},{5,6}}",
    answer4: "{{1,2,3},{4,{5,}},6,{{7}}}",
    correct_answer: 4,
    explaination: "Equivalent sets have the same number of members",
    hint: "Somethings equal",
    image: null,
    source: "Perth",
    question: "If A={1,2,3,4} which one is equivalent set of set A",
    skillLevel: 1,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "A={$x:x\\in\\mathbb{N}$ and $x^3=8$}",
    answer2: "B={$x:x\\in\\mathbb{N}$ and $x-10=-10$}",
    answer3: "C={$x:x\\in\\mathbb{N}$ and $x+1=10$}",
    answer4: "D={$x:x\\in\\mathbb{N}$ and $x^2=9$}",
    correct_answer: 2,
    explaination: "A set with no member inside",
    hint: "Not any member",
    image: null,
    source: "Perth",
    question: "Which one is a null set",
    skillLevel: 1,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "A={$x:x\\in\\mathbb{R}$ and $x^2=4$}",
    answer2: "B={$x:x\\in\\mathbb{R}$ and $0\\div x=0$}",
    answer3: "C={$x:x\\in\\mathbb{R}$ and $x\\cdot 0=1$}",
    answer4: "D={$x:x\\in\\mathbb{R}$ and $x+x=14$}",
    correct_answer: 4,
    explaination: "Singleton set has only one member",
    hint: "One member",
    image: null,
    source: "Perth",
    question: "Which one is a singleton set",
    skillLevel: 2,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "A={$x:x\\in\\mathbb{R}$ and $\\sqrt[]x = 2 $}",
    answer2: "B={$x:x\\in\\mathbb{R}$ and $0< x<1$}",
    answer3: "C={$x:x\\in\\mathbb{N}$ and $0< x<1$}",
    answer4: "D={$x:x\\in\\mathbb{N}$ and $\\sqrt[]x = 2$}",
    correct_answer: 2,
    explaination: "Infinite set has infinite members",
    hint: "Infinite members",
    image: null,
    source: "Perth",
    question: "Which one is infinite set",
    skillLevel: 2,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "null set",
    answer2: "singleton set",
    answer3: "finite set",
    answer4: "infinite set",
    correct_answer: 3,
    explaination: "T={1,2,3,…,98}",
    hint: "$mathbb{N}$ is natural number",
    image: null,
    source: "Perth",
    question: "T={$x:x\\in \\mathbb{N}$ and $x<99$} What is a type of set T",
    skillLevel: 2,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "singleton set",
    answer2: "equivalent set",
    answer3: "infinite set",
    answer4: "null set",
    correct_answer: 1,
    explaination: "$P=\\{\\{1,2,3,4,5,6,7,8,9\\}\\}$",
    hint: "Natural number doesn’t have fractions and decimals",
    image: null,
    source: "Perth",
    question:
      "P={{$x:x\\in \\mathbb{N}$ and $x<10$}} What is the type of set P",
    skillLevel: 3,
    tags: ["sets", "type of sets"],
  },
  {
    answer1: "$A$ is singleton set and $B$ is finite set",
    answer2: "$A$ and $B$ are equal sets",
    answer3: "$A$ and $B$ are equivalent sets",
    answer4: "$A$ is null set and $B$ is singleton set",
    correct_answer: 4,
    explaination: "$A=\\{\\} and B=\\{27\\}$",
    hint: "Natural number doesn’t have fractions and decimals",
    image: null,
    source: "Perth",
    question:
      "If $A=\\{x:x\\in \\mathbb{N}$ and $x\\cdot2=1\\}$ and $B=\\{x:x\\in \\mathbb{N}$ and $x\\div3=9\\}$ Which one is the correct answer",
    skillLevel: 3,
    tags: ["sets", "type of sets"],
  },
];
